### ISSUE TITLE
Add adTech Provider

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#16]
Documentation: http://www.adtech-demo.com/API (also reachable on https://adtech.fluidtopics.net/search#!search;query=api)

API Access:
- USERNAME: platform.api.1502.1
- PASSWORD: U(912!kpw%
- SERVER_URL: https://ws-api.adtech.de
- LOGIN_SERVER_URL: https://iq.adtech.de

Adapting	the	configuration for	SSO
1. Ensure	that	ADTECH	has	enabled	your	ONE	BY	AOL:	AdServer UI	login	to	be	SSO	
compatible
2. Replace {USERNAME} with	your	SSO	user	name
3. Replace	{PASSWORD} with	your	SSO password
4. Replace	{SERVER_URL} with	your	location’s	server	URL.
5. Replace	{LOGIN_SERVER_URL} with	your	location’s	login	server	URL.
6. You	are	now	ready	to	run	the	SSO code.

**Comment by elbidone** [comment]
An example of implementation on ruby to check report: https://github.com/factorymedia/adtech-api-ruby-client

**Comment by danielindiano** [comment]
According to the last meetings, we'll get the Adtech provider data via daily mail with data attached sent to a specific account to be defined. So the the Provider Service will work as above:
-  Receives only the startDate and proccess only one day for now;
   - In the future, we can check the viability to proccess multiple days (meaning, multiple email attachments);
-  The AdtechService calls the lib EmailReader with using the date and recipient as filter;
-  The AdtechPresenter will work the same way the others;
