### ISSUE TITLE
Adtech Presenter

### ISSUE THREAD

**Issue by danielindiano** [meumobi/AMS.Connect#36]
Create the presenter method for the Adtech Provider

Above it follow an example file with the Adtech Data:
[343944_1502_1_1489805144101_csv.txt](https://github.com/meumobi/AMS.Connect/files/854987/343944_1502_1_1489805144101_csv.txt)

**Comment by elbidone** [comment]
![7oaea6ak1jftyug-tcrogm_9hje23cxuqnyktwta3cdnkwur2t--uprz_i6eegdwhqoym1yogoq6gxnmb_tugqadlicxdpqz4nnkge3q2cqzhbprsuxrpz2010dnxm3nqerhij2bvsckqunuucp9lwvcecwr9rpygoxesvvpoh3uch1du05ihvhvdnswtnd-3fz-jf7a1e3c9e0ukd5w-ldsdqf178fcjs8s8kola4vjf7tu](https://cloud.githubusercontent.com/assets/9011612/24366564/dd9063d4-12ef-11e7-9a87-5bdd06679b3b.png)
