### ISSUE TITLE
csv formats are not consistent: correlation table use "," as separator and unplugged.csv use ";"

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#70]

**Comment by elbidone** [comment]
should prefere ";", because some fields use "," on value outside double quotes

**Comment by elbidone** [comment]
should prefer "," because for some providers DFM can't use ";"
I've update unplugged today to use ","

**Comment by danconte72** [comment]
adserving.csv is the only file with ; delimiter that I found

**Comment by elbidone** [comment]
ok keep it this way. adserving.csv is not a file we own. Means all files owned by us are consistent and use `'` as csv delimiter
