### ISSUE TITLE
If sublime API returns an error (html page) the exception is not catched

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#77]
Below the ERROR raised on log when sublime returns an error, for example for [report of 08/09](http://limitless-sea-32755.herokuapp.com/sublime?start=2017-09-08&end=2017-09-08&mode=preview)
```
[2017-09-29 10:21:58] lumen.ERROR: ErrorException: array_map(): Argument #2 should be an array in /app/app/Services/sublime/SublimeService.php:122
```

Should catch it, log the error, without catch the daily cron stop on sublime provider and not perform others providers

**Comment by danconte72** [comment]
In order to launch the error you can put overwrite the $requestUrl on row 67. As this sample:
```php 
$requestUrl = "https://raw.githubusercontent.com/meumobi/AMS.Connect/master/composer.json";
```
