### ISSUE TITLE
Move correlation table from heroku static file to AWS S3

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#79]
It should allow DFM user to edit it without our support.

**Comment by elbidone** [comment]
On a [previous commit](https://github.com/meumobi/AMS.Connect/commit/b57befc52a681218b2f0acd91228851ef81a7132), I've migrated to [Storage façade](https://nicksilvestro.net/2016/05/28/adding-laravels-storage-facade-into-lumen). This migration aims to prepare the migration of static files from localhost to remote disk, as S3.

**Comment by danconte72** [comment]
Don't forget: 
```bash
$ composer install --ignore-platform-reqs
$ composer update 
$ docker-compose build
$ docker-compose up -d
```
