### ISSUE TITLE
filter by range date raises Error 'Method [validateAfterOrEqual] does not exist.'

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#8]
tested with https://limitless-sea-32755.herokuapp.com/rubicon?start=2017-01-12&end=2017-01-20

**Comment by danielindiano** [comment]
It occurs because of the version of Lumen. The ValidateAfterOrEqual works in version 5.4! I've commited the updated composer.lock, so the heroku will update the package to the right version;
