### ISSUE TITLE
Update S3 Storage to access a non-public file

### ISSUE THREAD

**Issue by danconte72** [meumobi/AMS.Connect#80]
This is related to #79.
- [IAM Policies](https://console.aws.amazon.com/iam/home#/policies)
- [Test Policies](https://policysim.aws.amazon.com/home/index.jsp?#users)
- [Documentation - Laravel](https://laravel.com/docs/5.1/filesystem#introduction)
- [Documentation - Adapter](https://flysystem.thephpleague.com/adapter/aws-s3-v3/)

**Comment by elbidone** [comment]
We migrate TDC to Google sheet, then this issue isn't relevant anymore
