### ISSUE TITLE
Heroku: manage INT env

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#86]

**Comment by danconte72** [comment]
### Requirements: 
- [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli#download-and-install)
- To be logged on heroku: ```$ heroku login ```
- Two projects on same heroku account: ```$ heroku create --remote appname```
### To-do
1. [Update](http://support.beanstalkapp.com/article/1000-how-do-i-rename-an-existing-git-remote) your remote heroku url name to herokuprod:
```bash
$ git remote rename heroku herokuprod
$ git remote -v
```
2. Add remote heroku new app: _'enigmatic-spire-11550.git' in this case_
```bash
git remote add herokuint git@heroku.com:enigmatic-spire-11550.git
```
### Environments to Push
```bash
$ git push herokuint master
$ git push herokuprod master 
```
### Important!
Don't forget to [set](https://devcenter.heroku.com/articles/multiple-environments#managing-staging-and-production-configurations) your Config Variables:
```bash
$ heroku config:set APP_DEBUG=true --remote herokuint
$ heroku config:set APP_DEBUG=false --remote herokuprod
```

**Comment by elbidone** [comment]
I add integration remote env w/ 
`$ git remote add staging git@heroku.com:enigmatic-spire-11550.git` 
and rename heroku to production 
`$ git remote rename heroku production`
Now I only need to setup env on .git/config w/ 
`$ git config heroku.remote staging`
all heroku commands will default to the staging app.

Source: [Heroku - multiple environments](https://devcenter.heroku.com/articles/multiple-environments#starting-from-an-existing-app)
