### ISSUE TITLE
setting start date on rubicon returns unexpected values

### ISSUE THREAD

**Issue by elbidone** [meumobi/AMS.Connect#9]
I've setted [start=2017-01-13](https://limitless-sea-32755.herokuapp.com/rubicon?start=2017-01-13) and expect results from 13/01 until yesterday but it returns results from 12/01 to 13/01
![screenshot_1_25_17__1_05_am](https://cloud.githubusercontent.com/assets/9011612/22276374/543e9f40-e29a-11e6-9e3f-3a73dbc8daa0.png)

**Comment by danielindiano** [comment]
@elbidone, I've just checked the request, and the parameters looks ok:
```
{
  "start": "2017-01-13T00:00:00+00:00",
  "end": "2017-01-24T23:59:59+00:00",
  "account": "publisher/14794",
  "dimensions": "date,site,site_id,zone,zone_id,size,size_id",
  "metrics": "ecpm,revenue,impressions,paid_impression"
}
```
Must check if this diference comes from the request or maybe it's something related to the timezone of dates (+00:00)

**Comment by elbidone** [comment]
I've tested with following url and it returns the correct values:
https://api.rubiconproject.com/analytics/v1/report/?account=publisher/14794&end=2016-10-25T23:59:59-0700&dimensions=date,site,zone,size,site_id,zone_id&metrics=ecpm,revenue,impressions,paid_impression&start=2016-10-25T00:00:00-0700

Maybe you should use the correct timezone `-0700`

**Comment by elbidone** [comment]
I'll send a mail to rubicon support to confirm this assumption

**Comment by elbidone** [comment]
Using -7000 on december it continues to retrieve data from 30/11. I've tested using -800 offset, and it works. Then it seems that we should sync AMS.Connect with [daylight saving time of Los Angeles](https://www.timeanddate.com/time/zone/usa/los-angeles)
